[package]
name = "feed"
version = "0.1.0"
authors = ["losfair <zhy20000919@hotmail.com>"]

[lib]
name = "feed"
crate-type = ["cdylib"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
